### ISSUE TITLE
[bug]: kubernetesClient.UpdateStatus() causes resourceVersion change which causes 'conflict' on next UpdateStatus call

### ISSUE THREAD

**Issue by tomitesh** [buehler/dotnet-operator-sdk#594] opened 2023-08-24 12:36 UTC
### Describe the bug

We employ this library to set up AWS infrastructure. Upon generating a resource (i.e SecurityGroup.yaml) within Kubernetes, our operator (utilizing dotnet-operator-sdk) initiates the creation or update of the corresponding SecurityGroup in AWS.

We utilize kubernetesClient.UpdateStatus() to modify the status field of a resource. In a single synchronization cycle, we need to invoke kubernetesClient.UpdateStatus() multiple times to log the creation of the security group, as well as the establishment of both ingress and egress rules within the said security group.

After upgrading to KubeOps version 7.4.2, we have noticed that any modifications made to the status field result in a modification to the resourceVersion. In contrast, in the previous version of KubeOps, changes to the status field did not lead to alterations in the resourceVersion.

Since invoking kubernetesClient.UpdateStatus() leads to a modification in the resource version, any subsequent call to kubernetesClient.UpdateStatus() encounters an exception (k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Conflict').

### To reproduce

1. install KubeOps version 7.4.2
2. create entity
3. modify status using sdk
4. it changes resourceVersion and subsequent status update result in exception "Conflict"

**exception details**

k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Conflict'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.ReplaceNamespacedCustomObjectStatusWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String name, String dryRun, String fieldManager, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.CustomObjectsOperationsExtensions.ReplaceNamespacedCustomObjectStatusAsync(ICustomObjectsOperations operations, Object body, String group, String version, String namespaceParameter, String plural, String name, String dryRun, String fieldManager, CancellationToken cancellationToken)
   at KubeOps.KubernetesClient.KubernetesClient.UpdateStatus[TResource](TResource resource)
   at Platform.Operators.Kubernetes.KubernetesClientExtensions.UpdateStatusWithConflictRetryAsync[TResource,TStatus](IKubernetesClient client, Action`1 statusUpdate, TResource resource, CancellationToken cancellationToken)
   at Platform.Operators.Kubernetes.KubernetesClientExtensions.UpdateStatusWithConflictRetryAsync[TResource,TStatus](IKubernetesClient client, Action`1 statusUpdate, TResource resource, CancellationToken cancellationToken)

### Expected behavior

it should not change resourceVersion when we update status field.

### Additional Context

k8s version : 1.26

**Comment by nelsonroliveira** [comment] 2023-08-25 16:19
[tomitesh](https://github.com/tomitesh) colleague here...

This may be caused by a misunderstanding on how this library is supposed to be used on our part, please ignore this issue for now, we will re-evaluate our approach and possibly close the issue on the next Tuesday.

**Comment by tillig** [comment] 2023-08-25 20:51
I ran into this myself just now. I was upgrading from a previous version of the KubeOps library (5.4.1 -> 7.4.2). I have a sort of "operator" where a deployed custom entity type ends up generating other deployed entities.

As part of the Reconcile loop it does:

```c#
// Add an entry to the `status` on the entity with "Progressing"
SetStatusAsProgressing(customEntity);
client.UpdateStatus(customEntity);
DeploySomeThingsOwnedByTheCustomEntity();
// Find that "Progressing" status and change it to "Deployed"
SetStatusAsDeployed(customEntity);
// Here's where I get the Conflict:
client.UpdateStatus(customEntity);
```

This is new since 5.4.1, which doesn't narrow it down a lot, but it looks like there was some pretty big change about seven months ago, I'm guessing with the 7.0 release.

What was a little confusing is that operations on the `IKubernetesClient` that mutate the object seem to return the updated object, but `UpdateStatus` does not, so it wasn't obvious that there would be a change to the resource version.

**Comment by nelsonroliveira** [comment] 2023-09-01 08:35
For now doing with a single operation and status update per reconcile "solved" the issue for us.

This is probably safer than forcing a status update on a entity that has since the start of the loop changed, as we can't be sure if it was our process or something else in the background that modified it

**Comment by buehler** [comment] 2023-10-06 13:20
this is fixed in v8

**Closed** 2023-11-23 12:05 UTC
Labels: bug
