### ISSUE TITLE
[bug]: Watcher stops watching custom resource after some time

### ISSUE THREAD

**Issue by OQCDoe** [buehler/dotnet-operator-sdk#763] opened 2024-05-17 15:29 UTC
### Describe the bug

I am deploying a pretty basic operator into our k8s cluster (v1.28.5) and after a while (around 1 hour) we receive this event in our log:

```
{"Timestamp":"2024-05-17 13:11:04Z","EventId":0,"LogLevel":"Debug","Category":"KubeOps.Operator.Watcher.LeaderAwareResourceWatcher","Message":"The watcher received a known error from the watched resource \u0022V1TestEntity\u0022. This indicates that there are no instances of this resource.","State":{"Message":"The watcher received a known error from the watched resource \u0022V1TestEntity\u0022. This indicates that there are no instances of this resource.","resource":"V1TestEntity","{OriginalFormat}":"The watcher received a known error from the watched resource \u0022{resource}\u0022. This indicates that there are no instances of this resource."}}
```

When deploying a custom resource after this message appears, the ReconcileAsync message doesnt get called an no further log messages are written.

### To reproduce

1. Write basic Operator with v9.1.0
2. Deploy Operator to k8s 1.28.5
3. Do not deploy any instances of the custom resource
4. Wait >1 hour
5. Deploy an instance of the CR
6. Operator does not fire

### Expected behavior

The Operator should reconcile CRs even after some time has passed and even if there are no instances of CRs for a while

### Additional Context

[_The relevant code_](https://github.com/buehler/dotnet-operator-sdk/blob/f2e31e8c2bb20b954fcaf606cc3b9591f378de64/src/KubeOps.Operator/Watcher/ResourceWatcher%7BTEntity%7D.cs#L261)

**Comment by buehler** [comment] 2024-05-29 08:07
Hey @OQCDoe 
Thanks for reporting, this seems to be a duplicate of #739.

**Closed by buehler** 2024-05-29 08:07 UTC
Labels: bug
