### ISSUE TITLE
Cannot resolve scoped service 'KubeOps.Operator.Controller.IEventQueue`1[MyOperator.Entities.V1DemoEntity]' from root provider

### ISSUE THREAD

**Issue by hemantkathuria** [buehler/dotnet-operator-sdk#450] opened 2022-06-06 02:33 UTC
**Describe the bug**
Not able to debug the sample operator in .Net 6.0. Getting the below exception.

**To Reproduce**
1) Created the sample project via template
2) Project is targeting KubeOps 6.5.3 and .Net 6.0
3) Did dotnet run install
4) Did dotnet run and got the below error

`Startup Leader Elector for operator "myoperator".
Unhandled exception. System.InvalidOperationException: Cannot resolve scoped service 'KubeOps.Operator.Controller.IEventQueue`1[MyOperator.Entities.V1DemoEntity]' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at KubeOps.Operator.Builder.OperatorBuilder.<>c__DisplayClass18_0.<AddOperatorBase>b__3(ControllerRegistration r)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at KubeOps.Operator.Controller.ResourceControllerManager.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at KubeOps.Operator.Commands.RunOperator.OnExecuteAsync()
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)`

**Comment by Silvenga** [comment] 2022-06-09 00:05
@hemantkathuria I think this is fixed via #437 - can you try and downgrade to [v6.5.2](https://github.com/buehler/dotnet-operator-sdk/releases/tag/v6.5.2)? I'm not sure what version v6.5.3 was based on, since there's no tag in this repo. I'm wondering if something got mixed up on release.

**Comment by frabe1579** [comment] 2022-06-13 15:01
Same problem here.
I've tried v6.5.2, v6.5.3, v6.5.1, all gives me same error.

Any other suggestion?

**Comment by buehler** [comment] 2022-06-14 06:29
I'm still kind of baffled why there is a version 6.5.3, but no tag in github...

**Comment by ewassef** [comment] 2022-06-15 21:43
Same here, not fixed with latest version on nuget as of june 15

**Comment by frabe1579** [comment] 2022-06-16 07:43
The latest functioning version seems to be 6.3.1

**Comment by hemantkathuria** [comment] 2022-06-17 03:35
Yes, at least the above error goes away, If I downgrade to 6.3.1. Since I am doing this for the first time, facing few more issues.

1) I did "dotnet run --install" and it installed only the CRD but no container. Once done, I did F5 in VS and the above error don't show up. Do we need to have container running in local K8s for debugging? I assume, No..

2) Since CRD is created, I tried creating the custom resource with be below YAML. My understanding was on create it will HIT the breakpoint in my VS, is the expectation correct? :) But instead I see the below error.

`kubectl apply -f C:\CustomResource\CustomResource.yml
Error from server (InternalError): error when creating "C:\\CustomResource\\CustomResource.yml": Internal error occurred: failed calling webhook "myoperator.webhooks.v1demoentity.demomutator": failed to call webhook: Post "https://myoperator.myoperator-system.svc:443/demo.kubeops.dev/v1/demoentitys/demomutator/mutate?timeout=10s": service "myoperator" not found`

2) My console is showing this error constantly. I have not made any changes to DemoEntity

`fail: KubeOps.Operator.Kubernetes.ResourceWatcher[0]
      There was an error while watching the resource "MyOperator.Entities.V1DemoEntity".
      Microsoft.Rest.SerializationException: Unable to deserialize the response.
       ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
       ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
         at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.ReadAllUsingOptions[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonSerializerOptions options)
         at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable`1 watch, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable`1 watch, CancellationToken cancellationToken)
         at k8s.Kubernetes.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
         at k8s.WatcherExt.<>c__DisplayClass1_0`2.<<MakeStreamReaderCreator>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at k8s.Watcher`1.<>c.<CreateWatchEventEnumerator>b__21_1[TR](Task`1 t)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
         at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
         at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)`

**Comment by erin-allison** [comment] 2022-06-20 12:16
Don't do this! Building a new service provider for each controller is not a solution. It will create a disjointed dependency tree and multiple extra instances of a handful of services.

**Comment by rcm-steve-horne** [comment] 2022-06-20 12:22
Noted. Is it safe to call BuildServiceProvider ahead of time & pass the resulting instance in, or is there another approach we should be taking here?

**Comment by rcm-steve-horne** [comment] 2022-06-20 12:24
Noted, will look for another solution.

**Comment by erin-allison** [comment] 2022-06-20 12:25
I can't say easily based off what's in here - the one stack trace is poorly formatted to the point it's difficult to read and I have been too busy as of late to dig into this one.

**Comment by rcm-steve-horne** [comment] 2022-06-20 16:45
So https://stackoverflow.com/questions/55089755/cannot-resolve-scoped-service suggests we should be creating a service scope if we want to inject something with a scoped lifetime? In the meantime I've got this working locally by disabling scope validation (not proposed as a fix but might be useful to someone until this is fixed properly):

`builder.Host.UseDefaultServiceProvider(i => i.ValidateScopes = false);`

**Comment by Silvenga** [comment] 2022-06-20 16:46
Ugh, I dislike the default DependencyInjection container, its errors aren't the most useful. Using AutoFac, I'm not seeing any issues (https://github.com/Contrast-Security-OSS/agent-operator/blob/master/src/Contrast.K8s.AgentOperator/Startup.cs#L61) - pinned at a version close to latest.

Hopefully I'll have time a bit later to repo this. I wonder if the assemblies got mixed up. The error looks correct.

`ResourceControllerManager` is added as a hosted service, which defaults to singleton scope. It's requesting the activation of `IEventQueue` which is bound in request scope via the activation of the transient scoped `IManagedResourceController` (which any good DI container should provide in their error messages). 

In AutoFac, activating a request scoped service outside of a request scope creates a binding to the singleton scope by default. The default DependencyInjection resolves this ambiguity the other direction, by breaking.

The correct fix is by making the whole dependency graph either not-request-scoped, or request-scoped (since making a default request scope is only an option in the more advanced DI containers). Since the `ResourceControllerManager` is a hosted controller in singleton scope, effectively all `IManagedResourceController` are in transitive singleton scope (which includes `IEventQueue`). So either the `ResourceControllerManager` has to create a fake request scope that's bound in transitive singleton scope, or `IEventQueue` should be transitive/singleton scope.

**Comment by erin-allison** [comment] 2022-06-20 17:25
Actually it looks like while you are correct in the majority of that issue, the real trouble here is in the factory method I built, it attempts to resolve a couple scoped services directly from the root of the DI container, outside of any lifetime scope... and that is a big no-no.

https://github.com/buehler/dotnet-operator-sdk/blob/13f52c76059481181f8b1b53e84c0e6096753eef/src/KubeOps/Operator/Builder/OperatorBuilder.cs#L177-L182

This should be fairly easy to fix.

**Comment by erin-allison** [comment] 2022-06-20 17:34
Oh wow, yeah, when I wrote that function.... I don't know...

That violates a few best practices since it captures that service provider into the service instance as well.

**Comment by erin-allison** [comment] 2022-06-20 19:15
I couldn't reproduce the issue with the included TestOperator on v6.5.3 or latest master (though there was only 1 commit difference). Can someone who can reproduce the issue (@rcm-steve-horne) test against my fork with some changes?

https://github.com/buehler/dotnet-operator-sdk/compare/master...erin-allison:FixServiceLifetimes

**Comment by rcm-steve-horne** [comment] 2022-06-20 20:10
That change fixes the crash, thanks! That said I'm trying to use IEventQueue to kick off reconciliation events on owner objects when a child's status updates by having the parent controller watch the children & invoke IEventQueue.EnqueueLocal on changes; on my local branch that worked as I just flipped everything to singleton, but with your change that no longer works (presumably because the event queue is now scoped to individual requests).

I'm guessing my approach here is wrong, would appreciate any advice - if I should open a new ticket for this let me know.

**Comment by erin-allison** [comment] 2022-06-20 20:50
Let's keep this thread for the issue at hand. Discussions are a better place for that type of question. That being said, I do have some ideas that I will just need to flesh out a bit more.

**Comment by ewassef** [comment] 2022-08-03 19:53
I feel this has been abandoned... right now the current package in nuget is broken

**Comment by buehler** [comment] 2022-08-04 06:28
It is not, but I currently do not have the time to do much. You can certainly create a PR ;-)

As soon as I find the time, I'm going to develop it further.

**Closed** 2022-08-10 07:55 UTC
Labels: bug
